services:
  frontend:
    build: ./website
    container_name: orcs_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./website:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: orcs_backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - HOST=db
    privileged: true
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    container_name: orcs_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orcs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/migrations/000001_init_mg.up.sql:/docker-entrypoint-initdb.d/000001_init_mg.up.sql
      - ./backend/database/migrations/000002_update_user_table.up.sql:/docker-entrypoint-initdb.d/000002_update_user_table.up.sql
      - ./backend/database/migrations/000003_deployment.up.sql:/docker-entrypoint-initdb.d/000003_deployment.up.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d orcs"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
