CREATE TABLE IF NOT EXISTS deployment_containers (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    deployment_id INTEGER NOT NULL REFERENCES deployments(id) ON DELETE CASCADE,
    container_id TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
